# Form implementation generated from reading ui file 'E:\Projects\QT6\Enema\plugins\mssql\ui\add_user.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addUserWidget(object):
    def setupUi(self, addUserWidget):
        addUserWidget.setObjectName("addUserWidget")
        addUserWidget.resize(322, 78)
        addUserWidget.setMinimumSize(QtCore.QSize(322, 78))
        addUserWidget.setMaximumSize(QtCore.QSize(322, 78))
        self.groupBox_5 = QtWidgets.QGroupBox(parent=addUserWidget)
        self.groupBox_5.setGeometry(QtCore.QRect(-10, -10, 411, 101))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineUsername = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineUsername.setGeometry(QtCore.QRect(80, 20, 90, 20))
        self.lineUsername.setText("")
        self.lineUsername.setObjectName("lineUsername")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 61, 20))
        self.label_16.setObjectName("label_16")
        self.linePassword = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.linePassword.setGeometry(QtCore.QRect(80, 40, 90, 20))
        self.linePassword.setText("")
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.linePassword.setObjectName("linePassword")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(20, 40, 61, 20))
        self.label_17.setObjectName("label_17")
        self.addUserButton = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.addUserButton.setGeometry(QtCore.QRect(260, 29, 61, 21))
        self.addUserButton.setObjectName("addUserButton")
        self.radioSql = QtWidgets.QRadioButton(parent=self.groupBox_5)
        self.radioSql.setGeometry(QtCore.QRect(180, 20, 51, 17))
        self.radioSql.setChecked(True)
        self.radioSql.setObjectName("radioSql")
        self.radioWin = QtWidgets.QRadioButton(parent=self.groupBox_5)
        self.radioWin.setGeometry(QtCore.QRect(180, 40, 91, 17))
        self.radioWin.setObjectName("radioWin")
        self.progressBar = QtWidgets.QProgressBar(parent=self.groupBox_5)
        self.progressBar.setGeometry(QtCore.QRect(20, 70, 301, 10))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(addUserWidget)
        QtCore.QMetaObject.connectSlotsByName(addUserWidget)

    def retranslateUi(self, addUserWidget):
        _translate = QtCore.QCoreApplication.translate
        addUserWidget.setWindowTitle(_translate("addUserWidget", "Add user"))
        self.label_16.setText(_translate("addUserWidget", "Username:"))
        self.label_17.setText(_translate("addUserWidget", "Password:"))
        self.addUserButton.setText(_translate("addUserWidget", "Add"))
        self.radioSql.setText(_translate("addUserWidget", "sql"))
        self.radioWin.setText(_translate("addUserWidget", "windows"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addUserWidget = QtWidgets.QWidget()
    ui = Ui_addUserWidget()
    ui.setupUi(addUserWidget)
    addUserWidget.show()
    sys.exit(app.exec())
