# Form implementation generated from reading ui file 'E:\Projects\QT6\Enema\plugins\mssql\ui\ftp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ftpWidget(object):
    def setupUi(self, ftpWidget):
        ftpWidget.setObjectName("ftpWidget")
        ftpWidget.resize(431, 98)
        ftpWidget.setMinimumSize(QtCore.QSize(431, 98))
        ftpWidget.setMaximumSize(QtCore.QSize(431, 98))
        self.groupBox_2 = QtWidgets.QGroupBox(parent=ftpWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(-10, -10, 451, 121))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 31, 20))
        self.label_9.setObjectName("label_9")
        self.lineIP = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineIP.setGeometry(QtCore.QRect(50, 20, 101, 20))
        self.lineIP.setText("")
        self.lineIP.setObjectName("lineIP")
        self.lineFtpLogin = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineFtpLogin.setGeometry(QtCore.QRect(80, 40, 71, 20))
        self.lineFtpLogin.setText("")
        self.lineFtpLogin.setObjectName("lineFtpLogin")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 61, 20))
        self.label_10.setObjectName("label_10")
        self.lineFtpPwd = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineFtpPwd.setGeometry(QtCore.QRect(80, 60, 71, 20))
        self.lineFtpPwd.setText("")
        self.lineFtpPwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineFtpPwd.setObjectName("lineFtpPwd")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_11.setObjectName("label_11")
        self.lineFtpFile = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineFtpFile.setGeometry(QtCore.QRect(200, 20, 231, 20))
        self.lineFtpFile.setText("")
        self.lineFtpFile.setObjectName("lineFtpFile")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(160, 20, 31, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(160, 40, 41, 20))
        self.label_13.setObjectName("label_13")
        self.lineFtpPath = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineFtpPath.setGeometry(QtCore.QRect(200, 40, 231, 20))
        self.lineFtpPath.setText("")
        self.lineFtpPath.setObjectName("lineFtpPath")
        self.ftpButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.ftpButton.setGeometry(QtCore.QRect(340, 60, 91, 21))
        self.ftpButton.setFlat(False)
        self.ftpButton.setObjectName("ftpButton")
        self.radioGet = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioGet.setGeometry(QtCore.QRect(200, 60, 51, 17))
        self.radioGet.setChecked(True)
        self.radioGet.setObjectName("radioGet")
        self.radioSend = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioSend.setGeometry(QtCore.QRect(270, 60, 71, 17))
        self.radioSend.setObjectName("radioSend")
        self.progressBar = QtWidgets.QProgressBar(parent=self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(20, 90, 411, 10))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(ftpWidget)
        QtCore.QMetaObject.connectSlotsByName(ftpWidget)

    def retranslateUi(self, ftpWidget):
        _translate = QtCore.QCoreApplication.translate
        ftpWidget.setWindowTitle(_translate("ftpWidget", "FTP"))
        self.label_9.setText(_translate("ftpWidget", "IP:"))
        self.label_10.setText(_translate("ftpWidget", "Login:"))
        self.label_11.setText(_translate("ftpWidget", "Password:"))
        self.label_12.setText(_translate("ftpWidget", "Files:"))
        self.label_13.setText(_translate("ftpWidget", "Path:"))
        self.ftpButton.setText(_translate("ftpWidget", "GO"))
        self.radioGet.setText(_translate("ftpWidget", "GET"))
        self.radioSend.setText(_translate("ftpWidget", "SEND"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ftpWidget = QtWidgets.QWidget()
    ui = Ui_ftpWidget()
    ui.setupUi(ftpWidget)
    ftpWidget.show()
    sys.exit(app.exec())
