# Form implementation generated from reading ui file 'E:\Projects\QT6\Enema\plugins\mssql\ui\xp_cmdshell.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cmdshellWidget(object):
    def setupUi(self, cmdshellWidget):
        cmdshellWidget.setObjectName("cmdshellWidget")
        cmdshellWidget.resize(591, 618)
        cmdshellWidget.setMinimumSize(QtCore.QSize(591, 618))
        cmdshellWidget.setMaximumSize(QtCore.QSize(591, 618))
        self.tableWidget = QtWidgets.QTableWidget(parent=cmdshellWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 29, 571, 551))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(1500)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(1500)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(19)
        self.killButton = QtWidgets.QToolButton(parent=cmdshellWidget)
        self.killButton.setGeometry(QtCore.QRect(130, 590, 91, 20))
        self.killButton.setObjectName("killButton")
        self.lineCmd = QtWidgets.QLineEdit(parent=cmdshellWidget)
        self.lineCmd.setGeometry(QtCore.QRect(50, 8, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.lineCmd.setFont(font)
        self.lineCmd.setText("")
        self.lineCmd.setObjectName("lineCmd")
        self.enableButton = QtWidgets.QPushButton(parent=cmdshellWidget)
        self.enableButton.setGeometry(QtCore.QRect(10, 590, 111, 20))
        self.enableButton.setObjectName("enableButton")
        self.label_8 = QtWidgets.QLabel(parent=cmdshellWidget)
        self.label_8.setGeometry(QtCore.QRect(10, 9, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.progressBar = QtWidgets.QProgressBar(parent=cmdshellWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(230, 590, 351, 20))
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setToolTip("")
        self.progressBar.setStatusTip("")
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 4769)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.BottomToTop)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(cmdshellWidget)
        QtCore.QMetaObject.connectSlotsByName(cmdshellWidget)

    def retranslateUi(self, cmdshellWidget):
        _translate = QtCore.QCoreApplication.translate
        cmdshellWidget.setWindowTitle(_translate("cmdshellWidget", "xp_cmdshell"))
        self.killButton.setText(_translate("cmdshellWidget", "Kill"))
        self.enableButton.setText(_translate("cmdshellWidget", "Enabe xp_cmdshell"))
        self.label_8.setText(_translate("cmdshellWidget", "CMD>"))
        self.progressBar.setFormat(_translate("cmdshellWidget", "%p%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cmdshellWidget = QtWidgets.QWidget()
    ui = Ui_cmdshellWidget()
    ui.setupUi(cmdshellWidget)
    cmdshellWidget.show()
    sys.exit(app.exec())
