# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\enema\form.ui'
#
# Created: Sun Feb 26 08:55:45 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName(_fromUtf8("MainForm"))
        MainForm.resize(591, 618)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainForm.sizePolicy().hasHeightForWidth())
        MainForm.setSizePolicy(sizePolicy)
        MainForm.setMinimumSize(QtCore.QSize(591, 618))
        MainForm.setMaximumSize(QtCore.QSize(1112, 618))
        MainForm.setBaseSize(QtCore.QSize(0, 0))
        MainForm.setWindowTitle(_fromUtf8("Enema"))
        MainForm.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainForm.setDocumentMode(False)
        MainForm.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainForm)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 591, 601))
        self.tabWidget.setMinimumSize(QtCore.QSize(1, 1))
        self.tabWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(520, 10, 61, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainForm", "GET", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainForm", "POST", None, QtGui.QApplication.UnicodeUTF8))
        self.tablesButton = QtGui.QPushButton(self.tab)
        self.tablesButton.setGeometry(QtCore.QRect(10, 200, 91, 23))
        self.tablesButton.setText(QtGui.QApplication.translate("MainForm", "Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.tablesButton.setObjectName(_fromUtf8("tablesButton"))
        self.countButton = QtGui.QPushButton(self.tab)
        self.countButton.setGeometry(QtCore.QRect(110, 200, 91, 23))
        self.countButton.setText(QtGui.QApplication.translate("MainForm", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.countButton.setObjectName(_fromUtf8("countButton"))
        self.getColumnsButton = QtGui.QPushButton(self.tab)
        self.getColumnsButton.setGeometry(QtCore.QRect(210, 200, 91, 23))
        self.getColumnsButton.setText(QtGui.QApplication.translate("MainForm", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.getColumnsButton.setObjectName(_fromUtf8("getColumnsButton"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(410, 200, 171, 301))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(QtGui.QApplication.translate("MainForm", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioOrdinalPosition = QtGui.QRadioButton(self.groupBox)
        self.radioOrdinalPosition.setGeometry(QtCore.QRect(10, 90, 141, 17))
        self.radioOrdinalPosition.setText(QtGui.QApplication.translate("MainForm", "ordinal_position", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOrdinalPosition.setObjectName(_fromUtf8("radioOrdinalPosition"))
        self.radioNotInArray = QtGui.QRadioButton(self.groupBox)
        self.radioNotInArray.setGeometry(QtCore.QRect(10, 50, 141, 17))
        self.radioNotInArray.setText(QtGui.QApplication.translate("MainForm", "not in(array)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNotInArray.setChecked(True)
        self.radioNotInArray.setObjectName(_fromUtf8("radioNotInArray"))
        self.radioNotInSubstring = QtGui.QRadioButton(self.groupBox)
        self.radioNotInSubstring.setGeometry(QtCore.QRect(10, 70, 141, 17))
        self.radioNotInSubstring.setText(QtGui.QApplication.translate("MainForm", "not in(substring)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNotInSubstring.setChecked(False)
        self.radioNotInSubstring.setObjectName(_fromUtf8("radioNotInSubstring"))
        self.threadBox = QtGui.QSpinBox(self.groupBox)
        self.threadBox.setGeometry(QtCore.QRect(10, 180, 41, 20))
        self.threadBox.setMinimum(1)
        self.threadBox.setMaximum(100)
        self.threadBox.setProperty("value", 10)
        self.threadBox.setObjectName(_fromUtf8("threadBox"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 131, 20))
        self.label_5.setText(QtGui.QApplication.translate("MainForm", "Threads / Timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineTimeout = QtGui.QLineEdit(self.groupBox)
        self.lineTimeout.setGeometry(QtCore.QRect(60, 180, 41, 20))
        self.lineTimeout.setText(QtGui.QApplication.translate("MainForm", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.lineTimeout.setObjectName(_fromUtf8("lineTimeout"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("MainForm", "MSSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("MainForm", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.lineMS = QtGui.QLineEdit(self.groupBox)
        self.lineMS.setGeometry(QtCore.QRect(110, 140, 21, 20))
        self.lineMS.setText(QtGui.QApplication.translate("MainForm", "~", None, QtGui.QApplication.UnicodeUTF8))
        self.lineMS.setMaxLength(1)
        self.lineMS.setObjectName(_fromUtf8("lineMS"))
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 140, 91, 20))
        self.label_22.setText(QtGui.QApplication.translate("MainForm", "Match symbol:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 110, 101, 20))
        self.label_23.setText(QtGui.QApplication.translate("MainForm", "Match pattern:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineMP = QtGui.QLineEdit(self.groupBox)
        self.lineMP.setGeometry(QtCore.QRect(110, 110, 51, 20))
        self.lineMP.setText(_fromUtf8(""))
        self.lineMP.setObjectName(_fromUtf8("lineMP"))
        self.showLogButton = QtGui.QToolButton(self.groupBox)
        self.showLogButton.setGeometry(QtCore.QRect(40, 260, 91, 21))
        self.showLogButton.setText(QtGui.QApplication.translate("MainForm", "Show log ->", None, QtGui.QApplication.UnicodeUTF8))
        self.showLogButton.setObjectName(_fromUtf8("showLogButton"))
        self.lineUrl = QtGui.QLineEdit(self.tab)
        self.lineUrl.setGeometry(QtCore.QRect(40, 10, 471, 20))
        self.lineUrl.setText(_fromUtf8(""))
        self.lineUrl.setObjectName(_fromUtf8("lineUrl"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.label_4.setText(QtGui.QApplication.translate("MainForm", "URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 550, 71, 16))
        self.label.setText(QtGui.QApplication.translate("MainForm", "Tables total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.totalLabel = QtGui.QLabel(self.tab)
        self.totalLabel.setGeometry(QtCore.QRect(90, 550, 31, 16))
        self.totalLabel.setText(QtGui.QApplication.translate("MainForm", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.totalLabel.setObjectName(_fromUtf8("totalLabel"))
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(130, 550, 451, 16))
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setToolTip(_fromUtf8(""))
        self.progressBar.setStatusTip(_fromUtf8(""))
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 83210)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar.setFormat(QtGui.QApplication.translate("MainForm", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.cleanThreeButton = QtGui.QPushButton(self.tab)
        self.cleanThreeButton.setGeometry(QtCore.QRect(310, 200, 91, 23))
        self.cleanThreeButton.setText(QtGui.QApplication.translate("MainForm", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanThreeButton.setObjectName(_fromUtf8("cleanThreeButton"))
        self.listOfTables = QtGui.QListWidget(self.tab)
        self.listOfTables.setGeometry(QtCore.QRect(10, 230, 191, 311))
        self.listOfTables.setDragEnabled(True)
        self.listOfTables.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listOfTables.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listOfTables.setObjectName(_fromUtf8("listOfTables"))
        self.treeOfTables = QtGui.QTreeWidget(self.tab)
        self.treeOfTables.setGeometry(QtCore.QRect(210, 230, 191, 311))
        self.treeOfTables.setAcceptDrops(True)
        self.treeOfTables.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeOfTables.setDragDropOverwriteMode(True)
        self.treeOfTables.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.treeOfTables.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.treeOfTables.setIndentation(20)
        self.treeOfTables.setRootIsDecorated(True)
        self.treeOfTables.setUniformRowHeights(False)
        self.treeOfTables.setItemsExpandable(True)
        self.treeOfTables.setAnimated(True)
        self.treeOfTables.setWordWrap(False)
        self.treeOfTables.setColumnCount(1)
        self.treeOfTables.setObjectName(_fromUtf8("treeOfTables"))
        self.treeOfTables.headerItem().setText(0, QtGui.QApplication.translate("MainForm", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.treeOfTables.header().setVisible(False)
        self.treeOfTables.header().setCascadingSectionResizes(False)
        self.treeOfTables.header().setHighlightSections(False)
        self.dbListComboBox = QtGui.QComboBox(self.tab)
        self.dbListComboBox.setGeometry(QtCore.QRect(410, 520, 131, 21))
        self.dbListComboBox.setObjectName(_fromUtf8("dbListComboBox"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(490, 500, 41, 20))
        self.label_7.setText(QtGui.QApplication.translate("MainForm", "db:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.getBasesButton = QtGui.QToolButton(self.tab)
        self.getBasesButton.setGeometry(QtCore.QRect(550, 520, 31, 21))
        self.getBasesButton.setText(QtGui.QApplication.translate("MainForm", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.getBasesButton.setObjectName(_fromUtf8("getBasesButton"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 50, 571, 101))
        self.textEdit.setAcceptDrops(False)
        self.textEdit.setHtml(QtGui.QApplication.translate("MainForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 51, 21))
        self.label_3.setText(QtGui.QApplication.translate("MainForm", "Cookies:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineCookie = QtGui.QLineEdit(self.tab)
        self.lineCookie.setGeometry(QtCore.QRect(10, 170, 571, 21))
        self.lineCookie.setText(_fromUtf8(""))
        self.lineCookie.setObjectName(_fromUtf8("lineCookie"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.label_15.setText(QtGui.QApplication.translate("MainForm", "Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(200, 10, 71, 20))
        self.label_18.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_18.setText(QtGui.QApplication.translate("MainForm", "Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.label_19.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_19.setText(QtGui.QApplication.translate("MainForm", "Primary key:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(270, 40, 31, 20))
        self.label_20.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_20.setText(QtGui.QApplication.translate("MainForm", "To:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setEnabled(True)
        self.label_21.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.label_21.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_21.setText(QtGui.QApplication.translate("MainForm", "From:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineTable = QtGui.QLineEdit(self.tab_4)
        self.lineTable.setGeometry(QtCore.QRect(50, 10, 141, 20))
        self.lineTable.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineTable.setText(_fromUtf8(""))
        self.lineTable.setObjectName(_fromUtf8("lineTable"))
        self.lineTo = QtGui.QLineEdit(self.tab_4)
        self.lineTo.setGeometry(QtCore.QRect(300, 40, 71, 20))
        self.lineTo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineTo.setText(QtGui.QApplication.translate("MainForm", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.lineTo.setObjectName(_fromUtf8("lineTo"))
        self.lineColumns = QtGui.QLineEdit(self.tab_4)
        self.lineColumns.setGeometry(QtCore.QRect(260, 10, 321, 20))
        self.lineColumns.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineColumns.setText(_fromUtf8(""))
        self.lineColumns.setObjectName(_fromUtf8("lineColumns"))
        self.lineFrom = QtGui.QLineEdit(self.tab_4)
        self.lineFrom.setEnabled(True)
        self.lineFrom.setGeometry(QtCore.QRect(180, 40, 71, 20))
        self.lineFrom.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineFrom.setText(QtGui.QApplication.translate("MainForm", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineFrom.setObjectName(_fromUtf8("lineFrom"))
        self.lineKey = QtGui.QLineEdit(self.tab_4)
        self.lineKey.setGeometry(QtCore.QRect(80, 40, 41, 20))
        self.lineKey.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineKey.setText(_fromUtf8(""))
        self.lineKey.setObjectName(_fromUtf8("lineKey"))
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setText(QtGui.QApplication.translate("MainForm", "Table:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 571, 451))
        self.tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.dmpButton = QtGui.QCommandLinkButton(self.tab_4)
        self.dmpButton.setGeometry(QtCore.QRect(430, 30, 91, 41))
        self.dmpButton.setText(QtGui.QApplication.translate("MainForm", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.dmpButton.setObjectName(_fromUtf8("dmpButton"))
        self.progressBarDump = QtGui.QProgressBar(self.tab_4)
        self.progressBarDump.setEnabled(True)
        self.progressBarDump.setGeometry(QtCore.QRect(10, 550, 571, 16))
        self.progressBarDump.setAcceptDrops(False)
        self.progressBarDump.setToolTip(_fromUtf8(""))
        self.progressBarDump.setStatusTip(_fromUtf8(""))
        self.progressBarDump.setMaximum(0)
        self.progressBarDump.setProperty("value", 0)
        self.progressBarDump.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBarDump.setTextVisible(True)
        self.progressBarDump.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarDump.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBarDump.setFormat(QtGui.QApplication.translate("MainForm", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBarDump.setObjectName(_fromUtf8("progressBarDump"))
        self.label_14 = QtGui.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(190, 530, 321, 21))
        self.label_14.setText(QtGui.QApplication.translate("MainForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ff0000;\">WARNING: Separate thread pool for each column!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 431, 111))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainForm", "File Upload / Send (FTP)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 46, 20))
        self.label_9.setText(QtGui.QApplication.translate("MainForm", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineIP = QtGui.QLineEdit(self.groupBox_2)
        self.lineIP.setGeometry(QtCore.QRect(30, 20, 121, 20))
        self.lineIP.setText(_fromUtf8(""))
        self.lineIP.setObjectName(_fromUtf8("lineIP"))
        self.lineFtpLogin = QtGui.QLineEdit(self.groupBox_2)
        self.lineFtpLogin.setGeometry(QtCore.QRect(190, 20, 81, 20))
        self.lineFtpLogin.setText(_fromUtf8(""))
        self.lineFtpLogin.setObjectName(_fromUtf8("lineFtpLogin"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(160, 20, 46, 20))
        self.label_10.setText(QtGui.QApplication.translate("MainForm", "Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineFtpPwd = QtGui.QLineEdit(self.groupBox_2)
        self.lineFtpPwd.setGeometry(QtCore.QRect(330, 20, 91, 20))
        self.lineFtpPwd.setText(_fromUtf8(""))
        self.lineFtpPwd.setEchoMode(QtGui.QLineEdit.Password)
        self.lineFtpPwd.setObjectName(_fromUtf8("lineFtpPwd"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(280, 20, 61, 20))
        self.label_11.setText(QtGui.QApplication.translate("MainForm", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineFtpFile = QtGui.QLineEdit(self.groupBox_2)
        self.lineFtpFile.setGeometry(QtCore.QRect(40, 50, 381, 20))
        self.lineFtpFile.setText(_fromUtf8(""))
        self.lineFtpFile.setObjectName(_fromUtf8("lineFtpFile"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_12.setText(QtGui.QApplication.translate("MainForm", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 31, 20))
        self.label_13.setText(QtGui.QApplication.translate("MainForm", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineFtpPath = QtGui.QLineEdit(self.groupBox_2)
        self.lineFtpPath.setGeometry(QtCore.QRect(40, 80, 171, 20))
        self.lineFtpPath.setText(_fromUtf8(""))
        self.lineFtpPath.setObjectName(_fromUtf8("lineFtpPath"))
        self.ftpButton = QtGui.QPushButton(self.groupBox_2)
        self.ftpButton.setGeometry(QtCore.QRect(340, 82, 81, 21))
        self.ftpButton.setText(QtGui.QApplication.translate("MainForm", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.ftpButton.setFlat(False)
        self.ftpButton.setObjectName(_fromUtf8("ftpButton"))
        self.radioGet = QtGui.QRadioButton(self.groupBox_2)
        self.radioGet.setGeometry(QtCore.QRect(220, 80, 51, 17))
        self.radioGet.setText(QtGui.QApplication.translate("MainForm", "GET", None, QtGui.QApplication.UnicodeUTF8))
        self.radioGet.setChecked(True)
        self.radioGet.setObjectName(_fromUtf8("radioGet"))
        self.radioSend = QtGui.QRadioButton(self.groupBox_2)
        self.radioSend.setGeometry(QtCore.QRect(270, 80, 51, 17))
        self.radioSend.setText(QtGui.QApplication.translate("MainForm", "SEND", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSend.setObjectName(_fromUtf8("radioSend"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(450, 10, 131, 111))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainForm", "Add SQL admin", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lineAddUserLogin = QtGui.QLineEdit(self.groupBox_5)
        self.lineAddUserLogin.setGeometry(QtCore.QRect(60, 20, 61, 20))
        self.lineAddUserLogin.setText(_fromUtf8(""))
        self.lineAddUserLogin.setObjectName(_fromUtf8("lineAddUserLogin"))
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 46, 20))
        self.label_16.setText(QtGui.QApplication.translate("MainForm", "Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineAddUserPwd = QtGui.QLineEdit(self.groupBox_5)
        self.lineAddUserPwd.setGeometry(QtCore.QRect(70, 50, 51, 20))
        self.lineAddUserPwd.setText(_fromUtf8(""))
        self.lineAddUserPwd.setEchoMode(QtGui.QLineEdit.Password)
        self.lineAddUserPwd.setObjectName(_fromUtf8("lineAddUserPwd"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 61, 20))
        self.label_17.setText(QtGui.QApplication.translate("MainForm", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.addUserButton = QtGui.QPushButton(self.groupBox_5)
        self.addUserButton.setGeometry(QtCore.QRect(30, 80, 81, 23))
        self.addUserButton.setText(QtGui.QApplication.translate("MainForm", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.addUserButton.setObjectName(_fromUtf8("addUserButton"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 571, 291))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainForm", "Query", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.queryButton = QtGui.QPushButton(self.groupBox_3)
        self.queryButton.setGeometry(QtCore.QRect(10, 260, 101, 23))
        self.queryButton.setText(QtGui.QApplication.translate("MainForm", "Query", None, QtGui.QApplication.UnicodeUTF8))
        self.queryButton.setObjectName(_fromUtf8("queryButton"))
        self.queryText = QtGui.QTextEdit(self.groupBox_3)
        self.queryText.setGeometry(QtCore.QRect(10, 30, 551, 101))
        self.queryText.setDocumentTitle(_fromUtf8(""))
        self.queryText.setObjectName(_fromUtf8("queryText"))
        self.queryOutput = QtGui.QTextEdit(self.groupBox_3)
        self.queryOutput.setGeometry(QtCore.QRect(10, 170, 551, 81))
        self.queryOutput.setDocumentTitle(_fromUtf8(""))
        self.queryOutput.setReadOnly(True)
        self.queryOutput.setObjectName(_fromUtf8("queryOutput"))
        self.radioSelect = QtGui.QRadioButton(self.groupBox_3)
        self.radioSelect.setGeometry(QtCore.QRect(10, 140, 91, 17))
        self.radioSelect.setText(QtGui.QApplication.translate("MainForm", " SELECT TOP", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSelect.setChecked(True)
        self.radioSelect.setObjectName(_fromUtf8("radioSelect"))
        self.radioExec = QtGui.QRadioButton(self.groupBox_3)
        self.radioExec.setGeometry(QtCore.QRect(100, 140, 151, 17))
        self.radioExec.setText(QtGui.QApplication.translate("MainForm", "DECLARE, etc...", None, QtGui.QApplication.UnicodeUTF8))
        self.radioExec.setObjectName(_fromUtf8("radioExec"))
        self.openRowSetButton = QtGui.QPushButton(self.groupBox_3)
        self.openRowSetButton.setGeometry(QtCore.QRect(440, 260, 121, 23))
        self.openRowSetButton.setText(QtGui.QApplication.translate("MainForm", "Enable openrowset", None, QtGui.QApplication.UnicodeUTF8))
        self.openRowSetButton.setObjectName(_fromUtf8("openRowSetButton"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("MainForm", "CMD>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineCmd = QtGui.QLineEdit(self.tab_2)
        self.lineCmd.setGeometry(QtCore.QRect(50, 9, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineCmd.setFont(font)
        self.lineCmd.setText(_fromUtf8(""))
        self.lineCmd.setObjectName(_fromUtf8("lineCmd"))
        self.progressBarCmd = QtGui.QProgressBar(self.tab_2)
        self.progressBarCmd.setEnabled(True)
        self.progressBarCmd.setGeometry(QtCore.QRect(140, 541, 441, 20))
        self.progressBarCmd.setAcceptDrops(False)
        self.progressBarCmd.setToolTip(_fromUtf8(""))
        self.progressBarCmd.setStatusTip(_fromUtf8(""))
        self.progressBarCmd.setMaximum(0)
        self.progressBarCmd.setProperty("value", 4769)
        self.progressBarCmd.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBarCmd.setTextVisible(True)
        self.progressBarCmd.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarCmd.setInvertedAppearance(False)
        self.progressBarCmd.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBarCmd.setFormat(QtGui.QApplication.translate("MainForm", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBarCmd.setObjectName(_fromUtf8("progressBarCmd"))
        self.enableXpcmdButton = QtGui.QPushButton(self.tab_2)
        self.enableXpcmdButton.setGeometry(QtCore.QRect(10, 540, 121, 23))
        self.enableXpcmdButton.setText(QtGui.QApplication.translate("MainForm", "Enabe xp_cmdshell", None, QtGui.QApplication.UnicodeUTF8))
        self.enableXpcmdButton.setObjectName(_fromUtf8("enableXpcmdButton"))
        self.cmdOutput = QtGui.QTableWidget(self.tab_2)
        self.cmdOutput.setGeometry(QtCore.QRect(10, 30, 571, 501))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.cmdOutput.setFont(font)
        self.cmdOutput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cmdOutput.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.cmdOutput.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.cmdOutput.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.cmdOutput.setShowGrid(False)
        self.cmdOutput.setColumnCount(1)
        self.cmdOutput.setObjectName(_fromUtf8("cmdOutput"))
        self.cmdOutput.setRowCount(0)
        self.cmdOutput.horizontalHeader().setVisible(False)
        self.cmdOutput.horizontalHeader().setDefaultSectionSize(1500)
        self.cmdOutput.horizontalHeader().setMinimumSectionSize(1500)
        self.cmdOutput.verticalHeader().setVisible(False)
        self.cmdOutput.verticalHeader().setDefaultSectionSize(19)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.logTxtEdit = QtGui.QTextEdit(self.centralwidget)
        self.logTxtEdit.setGeometry(QtCore.QRect(600, 20, 501, 541))
        self.logTxtEdit.setReadOnly(True)
        self.logTxtEdit.setObjectName(_fromUtf8("logTxtEdit"))
        self.hideLogButton = QtGui.QToolButton(self.centralwidget)
        self.hideLogButton.setGeometry(QtCore.QRect(600, 570, 81, 21))
        self.hideLogButton.setText(QtGui.QApplication.translate("MainForm", "<- Hide log", None, QtGui.QApplication.UnicodeUTF8))
        self.hideLogButton.setObjectName(_fromUtf8("hideLogButton"))
        self.clearLogButton = QtGui.QToolButton(self.centralwidget)
        self.clearLogButton.setGeometry(QtCore.QRect(1020, 570, 81, 21))
        self.clearLogButton.setText(QtGui.QApplication.translate("MainForm", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.clearLogButton.setObjectName(_fromUtf8("clearLogButton"))
        MainForm.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSave = QtGui.QMenu(self.menubar)
        self.menuSave.setTitle(QtGui.QApplication.translate("MainForm", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuLoad = QtGui.QMenu(self.menubar)
        self.menuLoad.setTitle(QtGui.QApplication.translate("MainForm", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setTitle(QtGui.QApplication.translate("MainForm", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainForm", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainForm.setMenuBar(self.menubar)
        self.saveTables = QtGui.QAction(MainForm)
        self.saveTables.setText(QtGui.QApplication.translate("MainForm", "Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.saveTables.setObjectName(_fromUtf8("saveTables"))
        self.saveColumns = QtGui.QAction(MainForm)
        self.saveColumns.setText(QtGui.QApplication.translate("MainForm", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.saveColumns.setObjectName(_fromUtf8("saveColumns"))
        self.actionLoad_tables = QtGui.QAction(MainForm)
        self.actionLoad_tables.setText(QtGui.QApplication.translate("MainForm", "Load tables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_tables.setObjectName(_fromUtf8("actionLoad_tables"))
        self.actionLoad_columns = QtGui.QAction(MainForm)
        self.actionLoad_columns.setText(QtGui.QApplication.translate("MainForm", "Load columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_columns.setObjectName(_fromUtf8("actionLoad_columns"))
        self.actionLoad_tables_2 = QtGui.QAction(MainForm)
        self.actionLoad_tables_2.setText(QtGui.QApplication.translate("MainForm", "Load tables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_tables_2.setObjectName(_fromUtf8("actionLoad_tables_2"))
        self.loadTables = QtGui.QAction(MainForm)
        self.loadTables.setText(QtGui.QApplication.translate("MainForm", "Tables", None, QtGui.QApplication.UnicodeUTF8))
        self.loadTables.setObjectName(_fromUtf8("loadTables"))
        self.menuEncoder = QtGui.QAction(MainForm)
        self.menuEncoder.setText(QtGui.QApplication.translate("MainForm", "Encoder", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEncoder.setObjectName(_fromUtf8("menuEncoder"))
        self.menuDump = QtGui.QAction(MainForm)
        self.menuDump.setText(QtGui.QApplication.translate("MainForm", "Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDump.setObjectName(_fromUtf8("menuDump"))
        self.saveBases = QtGui.QAction(MainForm)
        self.saveBases.setText(QtGui.QApplication.translate("MainForm", "Bases", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBases.setObjectName(_fromUtf8("saveBases"))
        self.actionAll = QtGui.QAction(MainForm)
        self.actionAll.setText(QtGui.QApplication.translate("MainForm", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAll.setObjectName(_fromUtf8("actionAll"))
        self.loadBases = QtGui.QAction(MainForm)
        self.loadBases.setText(QtGui.QApplication.translate("MainForm", "Bases", None, QtGui.QApplication.UnicodeUTF8))
        self.loadBases.setObjectName(_fromUtf8("loadBases"))
        self.menuAbout = QtGui.QAction(MainForm)
        self.menuAbout.setText(QtGui.QApplication.translate("MainForm", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.csvExport = QtGui.QAction(MainForm)
        self.csvExport.setText(QtGui.QApplication.translate("MainForm", "Dump to csv", None, QtGui.QApplication.UnicodeUTF8))
        self.csvExport.setObjectName(_fromUtf8("csvExport"))
        self.save_cmdshell = QtGui.QAction(MainForm)
        self.save_cmdshell.setText(QtGui.QApplication.translate("MainForm", "xp_cmdshell output", None, QtGui.QApplication.UnicodeUTF8))
        self.save_cmdshell.setObjectName(_fromUtf8("save_cmdshell"))
        self.ssSettings = QtGui.QAction(MainForm)
        self.ssSettings.setText(QtGui.QApplication.translate("MainForm", "Site settings", None, QtGui.QApplication.UnicodeUTF8))
        self.ssSettings.setObjectName(_fromUtf8("ssSettings"))
        self.lsSettings = QtGui.QAction(MainForm)
        self.lsSettings.setText(QtGui.QApplication.translate("MainForm", "Site settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lsSettings.setObjectName(_fromUtf8("lsSettings"))
        self.lpSettings = QtGui.QAction(MainForm)
        self.lpSettings.setText(QtGui.QApplication.translate("MainForm", "Program settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lpSettings.setObjectName(_fromUtf8("lpSettings"))
        self.spSettings = QtGui.QAction(MainForm)
        self.spSettings.setText(QtGui.QApplication.translate("MainForm", "Program settings", None, QtGui.QApplication.UnicodeUTF8))
        self.spSettings.setObjectName(_fromUtf8("spSettings"))
        self.qEditor = QtGui.QAction(MainForm)
        self.qEditor.setText(QtGui.QApplication.translate("MainForm", "Query editor", None, QtGui.QApplication.UnicodeUTF8))
        self.qEditor.setObjectName(_fromUtf8("qEditor"))
        self.menuSave.addAction(self.saveTables)
        self.menuSave.addAction(self.saveColumns)
        self.menuSave.addAction(self.saveBases)
        self.menuSave.addAction(self.csvExport)
        self.menuSave.addAction(self.save_cmdshell)
        self.menuSave.addSeparator()
        self.menuSave.addAction(self.ssSettings)
        self.menuSave.addAction(self.spSettings)
        self.menuLoad.addAction(self.loadTables)
        self.menuLoad.addAction(self.loadBases)
        self.menuLoad.addSeparator()
        self.menuLoad.addAction(self.lsSettings)
        self.menuTools.addAction(self.menuEncoder)
        self.menuTools.addAction(self.qEditor)
        self.menuHelp.addAction(self.menuAbout)
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuLoad.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainForm)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        self.treeOfTables.setSortingEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainForm", "db structure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainForm", "dump", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainForm", "upload / query", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainForm", "xp_cmdshell", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainForm = QtGui.QMainWindow()
    ui = Ui_MainForm()
    ui.setupUi(MainForm)
    MainForm.show()
    sys.exit(app.exec_())

