# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\enema-dev\gui\main\query_editor.ui'
#
# Created: Sat Mar 10 14:46:29 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QueryEditorForm(object):
    def setupUi(self, QueryEditorForm):
        QueryEditorForm.setObjectName(_fromUtf8("QueryEditorForm"))
        QueryEditorForm.resize(869, 437)
        QueryEditorForm.setMinimumSize(QtCore.QSize(869, 437))
        QueryEditorForm.setMaximumSize(QtCore.QSize(869, 437))
        self.centralWidget = QtGui.QWidget(QueryEditorForm)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.qeTabWidget = QtGui.QTabWidget(self.centralWidget)
        self.qeTabWidget.setGeometry(QtCore.QRect(0, 0, 871, 481))
        self.qeTabWidget.setDocumentMode(True)
        self.qeTabWidget.setObjectName(_fromUtf8("qeTabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget = QtGui.QTabWidget(self.tab)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.q_ms_get_db_name = QtGui.QLineEdit(self.tab_3)
        self.q_ms_get_db_name.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_db_name.setFont(font)
        self.q_ms_get_db_name.setText(_fromUtf8(""))
        self.q_ms_get_db_name.setObjectName(_fromUtf8("q_ms_get_db_name"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.q_ms_dbs_count = QtGui.QLineEdit(self.tab_3)
        self.q_ms_dbs_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_dbs_count.setFont(font)
        self.q_ms_dbs_count.setText(_fromUtf8(""))
        self.q_ms_dbs_count.setObjectName(_fromUtf8("q_ms_dbs_count"))
        self.q_ms_curr_db_name = QtGui.QLineEdit(self.tab_3)
        self.q_ms_curr_db_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_curr_db_name.setFont(font)
        self.q_ms_curr_db_name.setText(_fromUtf8(""))
        self.q_ms_curr_db_name.setObjectName(_fromUtf8("q_ms_curr_db_name"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.q_ms_get_db_name2 = QtGui.QLineEdit(self.tab_3)
        self.q_ms_get_db_name2.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_db_name2.setFont(font)
        self.q_ms_get_db_name2.setText(_fromUtf8(""))
        self.q_ms_get_db_name2.setObjectName(_fromUtf8("q_ms_get_db_name2"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.q_ms_get_tbl_name = QtGui.QLineEdit(self.tab_4)
        self.q_ms_get_tbl_name.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_tbl_name.setFont(font)
        self.q_ms_get_tbl_name.setText(_fromUtf8(""))
        self.q_ms_get_tbl_name.setObjectName(_fromUtf8("q_ms_get_tbl_name"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.q_ms_get_tbl_name2 = QtGui.QLineEdit(self.tab_4)
        self.q_ms_get_tbl_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_tbl_name2.setFont(font)
        self.q_ms_get_tbl_name2.setText(_fromUtf8(""))
        self.q_ms_get_tbl_name2.setObjectName(_fromUtf8("q_ms_get_tbl_name2"))
        self.q_ms_tbls_count = QtGui.QLineEdit(self.tab_4)
        self.q_ms_tbls_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_tbls_count.setFont(font)
        self.q_ms_tbls_count.setText(_fromUtf8(""))
        self.q_ms_tbls_count.setObjectName(_fromUtf8("q_ms_tbls_count"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.q_ms_get_column_name = QtGui.QLineEdit(self.tab_5)
        self.q_ms_get_column_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_column_name.setFont(font)
        self.q_ms_get_column_name.setText(_fromUtf8(""))
        self.q_ms_get_column_name.setObjectName(_fromUtf8("q_ms_get_column_name"))
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(10, 110, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.q_ms_get_column_name3 = QtGui.QLineEdit(self.tab_5)
        self.q_ms_get_column_name3.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_column_name3.setFont(font)
        self.q_ms_get_column_name3.setText(_fromUtf8(""))
        self.q_ms_get_column_name3.setObjectName(_fromUtf8("q_ms_get_column_name3"))
        self.q_ms_columns_count = QtGui.QLineEdit(self.tab_5)
        self.q_ms_columns_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_columns_count.setFont(font)
        self.q_ms_columns_count.setText(_fromUtf8(""))
        self.q_ms_columns_count.setObjectName(_fromUtf8("q_ms_columns_count"))
        self.q_ms_get_column_name2 = QtGui.QLineEdit(self.tab_5)
        self.q_ms_get_column_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_column_name2.setFont(font)
        self.q_ms_get_column_name2.setText(_fromUtf8(""))
        self.q_ms_get_column_name2.setObjectName(_fromUtf8("q_ms_get_column_name2"))
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(10, 160, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.q_ms_rows_count = QtGui.QLineEdit(self.tab_7)
        self.q_ms_rows_count.setGeometry(QtCore.QRect(10, 30, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_rows_count.setFont(font)
        self.q_ms_rows_count.setText(_fromUtf8(""))
        self.q_ms_rows_count.setObjectName(_fromUtf8("q_ms_rows_count"))
        self.label_25 = QtGui.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.q_ms_query = QtGui.QLineEdit(self.tab_7)
        self.q_ms_query.setGeometry(QtCore.QRect(10, 80, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_query.setFont(font)
        self.q_ms_query.setText(_fromUtf8(""))
        self.q_ms_query.setObjectName(_fromUtf8("q_ms_query"))
        self.label_26 = QtGui.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.q_ms_data_dump = QtGui.QLineEdit(self.tab_7)
        self.q_ms_data_dump.setGeometry(QtCore.QRect(10, 130, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_data_dump.setFont(font)
        self.q_ms_data_dump.setText(_fromUtf8(""))
        self.q_ms_data_dump.setObjectName(_fromUtf8("q_ms_data_dump"))
        self.label_29 = QtGui.QLabel(self.tab_7)
        self.label_29.setGeometry(QtCore.QRect(10, 110, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(10, 210, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.q_ms_get_row = QtGui.QLineEdit(self.tab_7)
        self.q_ms_get_row.setGeometry(QtCore.QRect(10, 230, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_row.setFont(font)
        self.q_ms_get_row.setText(_fromUtf8(""))
        self.q_ms_get_row.setObjectName(_fromUtf8("q_ms_get_row"))
        self.q_ms_exec_cmdshell = QtGui.QLineEdit(self.tab_7)
        self.q_ms_exec_cmdshell.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_exec_cmdshell.setFont(font)
        self.q_ms_exec_cmdshell.setText(_fromUtf8(""))
        self.q_ms_exec_cmdshell.setObjectName(_fromUtf8("q_ms_exec_cmdshell"))
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.qeTabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.label_4 = QtGui.QLabel(self.tab_13)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_49 = QtGui.QLabel(self.tab_13)
        self.label_49.setGeometry(QtCore.QRect(10, 110, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.q_my_dbs_count = QtGui.QLineEdit(self.tab_13)
        self.q_my_dbs_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_dbs_count.setFont(font)
        self.q_my_dbs_count.setText(_fromUtf8(""))
        self.q_my_dbs_count.setObjectName(_fromUtf8("q_my_dbs_count"))
        self.q_my_curr_db_name = QtGui.QLineEdit(self.tab_13)
        self.q_my_curr_db_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_curr_db_name.setFont(font)
        self.q_my_curr_db_name.setText(_fromUtf8(""))
        self.q_my_curr_db_name.setObjectName(_fromUtf8("q_my_curr_db_name"))
        self.label_51 = QtGui.QLabel(self.tab_13)
        self.label_51.setGeometry(QtCore.QRect(10, 60, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.q_my_get_db_name2 = QtGui.QLineEdit(self.tab_13)
        self.q_my_get_db_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_db_name2.setFont(font)
        self.q_my_get_db_name2.setText(_fromUtf8(""))
        self.q_my_get_db_name2.setObjectName(_fromUtf8("q_my_get_db_name2"))
        self.tabWidget_2.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.label_53 = QtGui.QLabel(self.tab_14)
        self.label_53.setGeometry(QtCore.QRect(10, 60, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.q_my_get_tbl_name2 = QtGui.QLineEdit(self.tab_14)
        self.q_my_get_tbl_name2.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_tbl_name2.setFont(font)
        self.q_my_get_tbl_name2.setText(_fromUtf8(""))
        self.q_my_get_tbl_name2.setObjectName(_fromUtf8("q_my_get_tbl_name2"))
        self.q_my_tbls_count = QtGui.QLineEdit(self.tab_14)
        self.q_my_tbls_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_tbls_count.setFont(font)
        self.q_my_tbls_count.setText(_fromUtf8(""))
        self.q_my_tbls_count.setObjectName(_fromUtf8("q_my_tbls_count"))
        self.label_54 = QtGui.QLabel(self.tab_14)
        self.label_54.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.tabWidget_2.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.label_55 = QtGui.QLabel(self.tab_15)
        self.label_55.setGeometry(QtCore.QRect(10, 60, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.q_my_get_column_name3 = QtGui.QLineEdit(self.tab_15)
        self.q_my_get_column_name3.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_column_name3.setFont(font)
        self.q_my_get_column_name3.setText(_fromUtf8(""))
        self.q_my_get_column_name3.setObjectName(_fromUtf8("q_my_get_column_name3"))
        self.q_my_columns_count = QtGui.QLineEdit(self.tab_15)
        self.q_my_columns_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_columns_count.setFont(font)
        self.q_my_columns_count.setText(_fromUtf8(""))
        self.q_my_columns_count.setObjectName(_fromUtf8("q_my_columns_count"))
        self.q_my_get_column_name2 = QtGui.QLineEdit(self.tab_15)
        self.q_my_get_column_name2.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_column_name2.setFont(font)
        self.q_my_get_column_name2.setText(_fromUtf8(""))
        self.q_my_get_column_name2.setObjectName(_fromUtf8("q_my_get_column_name2"))
        self.label_56 = QtGui.QLabel(self.tab_15)
        self.label_56.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.tab_15)
        self.label_57.setGeometry(QtCore.QRect(10, 110, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.tabWidget_2.addTab(self.tab_15, _fromUtf8(""))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.q_my_rows_count = QtGui.QLineEdit(self.tab_17)
        self.q_my_rows_count.setGeometry(QtCore.QRect(10, 30, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_rows_count.setFont(font)
        self.q_my_rows_count.setText(_fromUtf8(""))
        self.q_my_rows_count.setObjectName(_fromUtf8("q_my_rows_count"))
        self.label_66 = QtGui.QLabel(self.tab_17)
        self.label_66.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.q_my_query = QtGui.QLineEdit(self.tab_17)
        self.q_my_query.setGeometry(QtCore.QRect(10, 80, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_query.setFont(font)
        self.q_my_query.setText(_fromUtf8(""))
        self.q_my_query.setObjectName(_fromUtf8("q_my_query"))
        self.label_67 = QtGui.QLabel(self.tab_17)
        self.label_67.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.tabWidget_2.addTab(self.tab_17, _fromUtf8(""))
        self.qeTabWidget.addTab(self.tab_2, _fromUtf8(""))
        QueryEditorForm.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(QueryEditorForm)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 869, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMenu = QtGui.QMenu(self.menuBar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        QueryEditorForm.setMenuBar(self.menuBar)
        self.qsSave = QtGui.QAction(QueryEditorForm)
        self.qsSave.setObjectName(_fromUtf8("qsSave"))
        self.qsRestore = QtGui.QAction(QueryEditorForm)
        self.qsRestore.setObjectName(_fromUtf8("qsRestore"))
        self.menuMenu.addAction(self.qsSave)
        self.menuMenu.addAction(self.qsRestore)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(QueryEditorForm)
        self.qeTabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QueryEditorForm)

    def retranslateUi(self, QueryEditorForm):
        QueryEditorForm.setWindowTitle(QtGui.QApplication.translate("QueryEditorForm", "Enema - Query Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QueryEditorForm", "------current db name------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (not in substring method, multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of databases------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("QueryEditorForm", "bases", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (not in substring method,multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of tables------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("QueryEditorForm", "tables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (not in substring method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("QueryEditorForm", "------columns count------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (ordinal_postition method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("QueryEditorForm", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("QueryEditorForm", "------rows count in selected table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("QueryEditorForm", "------run query------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("QueryEditorForm", "------data dump------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("QueryEditorForm", "------get row from temp table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("QueryEditorForm", "------exec xp_cmdshell------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("QueryEditorForm", "etc", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget.setTabText(self.qeTabWidget.indexOf(self.tab), QtGui.QApplication.translate("QueryEditorForm", "mssql", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("QueryEditorForm", "------current db name------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (limit method, multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of databases------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), QtGui.QApplication.translate("QueryEditorForm", "bases", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (limit method,multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of tables------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_14), QtGui.QApplication.translate("QueryEditorForm", "tables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (limit method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("QueryEditorForm", "------columns count------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (ordinal_postition method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_15), QtGui.QApplication.translate("QueryEditorForm", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("QueryEditorForm", "------rows count in selected table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("QueryEditorForm", "------run query------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_17), QtGui.QApplication.translate("QueryEditorForm", "etc", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget.setTabText(self.qeTabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("QueryEditorForm", "mysql", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("QueryEditorForm", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.qsSave.setText(QtGui.QApplication.translate("QueryEditorForm", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.qsRestore.setText(QtGui.QApplication.translate("QueryEditorForm", "Restore defaults", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QueryEditorForm = QtGui.QMainWindow()
    ui = Ui_QueryEditorForm()
    ui.setupUi(QueryEditorForm)
    QueryEditorForm.show()
    sys.exit(app.exec_())

