# Form implementation generated from reading ui file 'E:\Projects\QT6\Enema\ui\encoder.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EncoderForm(object):
    def setupUi(self, EncoderForm):
        EncoderForm.setObjectName("EncoderForm")
        EncoderForm.resize(467, 226)
        EncoderForm.setMinimumSize(QtCore.QSize(467, 226))
        EncoderForm.setMaximumSize(QtCore.QSize(467, 226))
        EncoderForm.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.lineString = QtWidgets.QLineEdit(parent=EncoderForm)
        self.lineString.setGeometry(QtCore.QRect(10, 10, 381, 20))
        self.lineString.setObjectName("lineString")
        self.encodeButton = QtWidgets.QPushButton(parent=EncoderForm)
        self.encodeButton.setGeometry(QtCore.QRect(400, 180, 61, 31))
        self.encodeButton.setObjectName("encodeButton")
        self.textResult = QtWidgets.QTextEdit(parent=EncoderForm)
        self.textResult.setGeometry(QtCore.QRect(10, 40, 451, 131))
        self.textResult.setReadOnly(True)
        self.textResult.setObjectName("textResult")
        self.radioHex = QtWidgets.QRadioButton(parent=EncoderForm)
        self.radioHex.setGeometry(QtCore.QRect(20, 180, 82, 17))
        self.radioHex.setChecked(True)
        self.radioHex.setObjectName("radioHex")
        self.radioChar = QtWidgets.QRadioButton(parent=EncoderForm)
        self.radioChar.setGeometry(QtCore.QRect(20, 200, 51, 17))
        self.radioChar.setChecked(False)
        self.radioChar.setObjectName("radioChar")
        self.isUrlencoded = QtWidgets.QCheckBox(parent=EncoderForm)
        self.isUrlencoded.setEnabled(True)
        self.isUrlencoded.setGeometry(QtCore.QRect(90, 180, 131, 17))
        self.isUrlencoded.setChecked(False)
        self.isUrlencoded.setObjectName("isUrlencoded")
        self.comboBox = QtWidgets.QComboBox(parent=EncoderForm)
        self.comboBox.setGeometry(QtCore.QRect(400, 10, 61, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.isPlay = QtWidgets.QCheckBox(parent=EncoderForm)
        self.isPlay.setEnabled(True)
        self.isPlay.setGeometry(QtCore.QRect(90, 200, 131, 17))
        self.isPlay.setChecked(False)
        self.isPlay.setObjectName("isPlay")
        self.decodeButton = QtWidgets.QPushButton(parent=EncoderForm)
        self.decodeButton.setGeometry(QtCore.QRect(330, 180, 61, 31))
        self.decodeButton.setObjectName("decodeButton")

        self.retranslateUi(EncoderForm)
        QtCore.QMetaObject.connectSlotsByName(EncoderForm)

    def retranslateUi(self, EncoderForm):
        _translate = QtCore.QCoreApplication.translate
        EncoderForm.setWindowTitle(_translate("EncoderForm", "Encoder"))
        self.encodeButton.setText(_translate("EncoderForm", "Encode"))
        self.radioHex.setText(_translate("EncoderForm", "Hex"))
        self.radioChar.setText(_translate("EncoderForm", "Char"))
        self.isUrlencoded.setText(_translate("EncoderForm", "Url-encoded"))
        self.comboBox.setItemText(0, _translate("EncoderForm", "MSSQL"))
        self.comboBox.setItemText(1, _translate("EncoderForm", "MySQL"))
        self.comboBox.setItemText(2, _translate("EncoderForm", "Base64"))
        self.isPlay.setText(_translate("EncoderForm", "Random UpCase"))
        self.decodeButton.setText(_translate("EncoderForm", "Decode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EncoderForm = QtWidgets.QWidget()
    ui = Ui_EncoderForm()
    ui.setupUi(EncoderForm)
    EncoderForm.show()
    sys.exit(app.exec())
