# Form implementation generated from reading ui file 'E:\Projects\QT6\Enema\ui\preferences.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_preferencesWidget(object):
    def setupUi(self, preferencesWidget):
        preferencesWidget.setObjectName("preferencesWidget")
        preferencesWidget.resize(262, 181)
        preferencesWidget.setMinimumSize(QtCore.QSize(262, 181))
        preferencesWidget.setMaximumSize(QtCore.QSize(262, 181))
        self.groupBox = QtWidgets.QGroupBox(parent=preferencesWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 241, 161))
        self.groupBox.setObjectName("groupBox")
        self.lineMP = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineMP.setGeometry(QtCore.QRect(160, 20, 41, 20))
        self.lineMP.setText("")
        self.lineMP.setObjectName("lineMP")
        self.lineMS = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineMS.setGeometry(QtCore.QRect(120, 20, 21, 20))
        self.lineMS.setMaxLength(1)
        self.lineMS.setObjectName("lineMS")
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(150, 20, 16, 20))
        self.label_23.setObjectName("label_23")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 51, 20))
        self.label_5.setObjectName("label_5")
        self.lineTimeout = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineTimeout.setGeometry(QtCore.QRect(160, 50, 41, 20))
        self.lineTimeout.setObjectName("lineTimeout")
        self.threadBox = QtWidgets.QSpinBox(parent=self.groupBox)
        self.threadBox.setGeometry(QtCore.QRect(60, 50, 41, 20))
        self.threadBox.setMinimum(1)
        self.threadBox.setMaximum(100)
        self.threadBox.setProperty("value", 5)
        self.threadBox.setObjectName("threadBox")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(110, 50, 51, 20))
        self.label_6.setObjectName("label_6")
        self.isRndUpper = QtWidgets.QCheckBox(parent=self.groupBox)
        self.isRndUpper.setGeometry(QtCore.QRect(10, 110, 111, 17))
        self.isRndUpper.setObjectName("isRndUpper")
        self.lineEncoding = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEncoding.setGeometry(QtCore.QRect(60, 80, 81, 20))
        self.lineEncoding.setObjectName("lineEncoding")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 61, 20))
        self.label_7.setObjectName("label_7")
        self.acceptCookies = QtWidgets.QCheckBox(parent=self.groupBox)
        self.acceptCookies.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.acceptCookies.setObjectName("acceptCookies")

        self.retranslateUi(preferencesWidget)
        QtCore.QMetaObject.connectSlotsByName(preferencesWidget)

    def retranslateUi(self, preferencesWidget):
        _translate = QtCore.QCoreApplication.translate
        preferencesWidget.setWindowTitle(_translate("preferencesWidget", "Preferences"))
        self.groupBox.setTitle(_translate("preferencesWidget", "Main"))
        self.lineMS.setText(_translate("preferencesWidget", "~"))
        self.label_22.setText(_translate("preferencesWidget", "Match symbol / string:"))
        self.label_23.setText(_translate("preferencesWidget", "/"))
        self.label_5.setText(_translate("preferencesWidget", "Threads:"))
        self.lineTimeout.setText(_translate("preferencesWidget", "60"))
        self.label_6.setText(_translate("preferencesWidget", "Timeout:"))
        self.isRndUpper.setText(_translate("preferencesWidget", "Random UpCase"))
        self.lineEncoding.setText(_translate("preferencesWidget", "windows-1251"))
        self.label_7.setText(_translate("preferencesWidget", "Encoding:"))
        self.acceptCookies.setText(_translate("preferencesWidget", "Accept cookies"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    preferencesWidget = QtWidgets.QWidget()
    ui = Ui_preferencesWidget()
    ui.setupUi(preferencesWidget)
    preferencesWidget.show()
    sys.exit(app.exec())
