# Form implementation generated from reading ui file 'E:\Projects\QT6\Enema\ui\query_editor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QueryEditorForm(object):
    def setupUi(self, QueryEditorForm):
        QueryEditorForm.setObjectName("QueryEditorForm")
        QueryEditorForm.resize(652, 452)
        QueryEditorForm.setMinimumSize(QtCore.QSize(652, 452))
        QueryEditorForm.setMaximumSize(QtCore.QSize(652, 452))
        self.treeQueryStrings = QtWidgets.QTreeWidget(parent=QueryEditorForm)
        self.treeQueryStrings.setGeometry(QtCore.QRect(10, 10, 631, 371))
        self.treeQueryStrings.setObjectName("treeQueryStrings")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeQueryStrings)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeQueryStrings)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeQueryStrings)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeQueryStrings)
        self.treeQueryStrings.header().setVisible(True)
        self.treeQueryStrings.header().setMinimumSectionSize(27)
        self.label = QtWidgets.QLabel(parent=QueryEditorForm)
        self.label.setGeometry(QtCore.QRect(10, 420, 161, 20))
        self.label.setObjectName("label")
        self.replaceButton = QtWidgets.QPushButton(parent=QueryEditorForm)
        self.replaceButton.setGeometry(QtCore.QRect(370, 420, 71, 20))
        self.replaceButton.setObjectName("replaceButton")
        self.lineFindStr = QtWidgets.QLineEdit(parent=QueryEditorForm)
        self.lineFindStr.setGeometry(QtCore.QRect(170, 420, 91, 20))
        self.lineFindStr.setObjectName("lineFindStr")
        self.lineResplaceStr = QtWidgets.QLineEdit(parent=QueryEditorForm)
        self.lineResplaceStr.setGeometry(QtCore.QRect(270, 420, 91, 20))
        self.lineResplaceStr.setObjectName("lineResplaceStr")
        self.defaultsButton = QtWidgets.QPushButton(parent=QueryEditorForm)
        self.defaultsButton.setGeometry(QtCore.QRect(570, 420, 71, 23))
        self.defaultsButton.setObjectName("defaultsButton")
        self.lineQueryString = QtWidgets.QLineEdit(parent=QueryEditorForm)
        self.lineQueryString.setGeometry(QtCore.QRect(10, 390, 631, 20))
        self.lineQueryString.setObjectName("lineQueryString")

        self.retranslateUi(QueryEditorForm)
        QtCore.QMetaObject.connectSlotsByName(QueryEditorForm)

    def retranslateUi(self, QueryEditorForm):
        _translate = QtCore.QCoreApplication.translate
        QueryEditorForm.setWindowTitle(_translate("QueryEditorForm", "Query Editor"))
        self.treeQueryStrings.headerItem().setText(0, _translate("QueryEditorForm", "Query strings"))
        __sortingEnabled = self.treeQueryStrings.isSortingEnabled()
        self.treeQueryStrings.setSortingEnabled(False)
        self.treeQueryStrings.topLevelItem(0).setText(0, _translate("QueryEditorForm", "MSSQL"))
        self.treeQueryStrings.topLevelItem(1).setText(0, _translate("QueryEditorForm", "MySQL"))
        self.treeQueryStrings.topLevelItem(2).setText(0, _translate("QueryEditorForm", "Oracle"))
        self.treeQueryStrings.topLevelItem(3).setText(0, _translate("QueryEditorForm", "PostgreSQL"))
        self.treeQueryStrings.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("QueryEditorForm", "Find & Replace (case sensitive):"))
        self.replaceButton.setText(_translate("QueryEditorForm", "Replace"))
        self.defaultsButton.setText(_translate("QueryEditorForm", "Defaults"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QueryEditorForm = QtWidgets.QWidget()
    ui = Ui_QueryEditorForm()
    ui.setupUi(QueryEditorForm)
    QueryEditorForm.show()
    sys.exit(app.exec())
