# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\enema\gui\main\query_editor.ui'
#
# Created: Thu Mar 15 21:22:16 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QueryEditorForm(object):
    def setupUi(self, QueryEditorForm):
        QueryEditorForm.setObjectName(_fromUtf8("QueryEditorForm"))
        QueryEditorForm.resize(861, 437)
        QueryEditorForm.setMinimumSize(QtCore.QSize(861, 437))
        QueryEditorForm.setMaximumSize(QtCore.QSize(861, 437))
        self.centralWidget = QtGui.QWidget(QueryEditorForm)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.qeTabWidget = QtGui.QTabWidget(self.centralWidget)
        self.qeTabWidget.setGeometry(QtCore.QRect(0, 0, 871, 481))
        self.qeTabWidget.setDocumentMode(True)
        self.qeTabWidget.setObjectName(_fromUtf8("qeTabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.qeTabWidget_3 = QtGui.QTabWidget(self.tab)
        self.qeTabWidget_3.setGeometry(QtCore.QRect(0, 0, 871, 481))
        self.qeTabWidget_3.setDocumentMode(True)
        self.qeTabWidget_3.setObjectName(_fromUtf8("qeTabWidget_3"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.tabWidget = QtGui.QTabWidget(self.tab_8)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 871, 371))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.q_ms_get_db_name = QtGui.QLineEdit(self.tab_3)
        self.q_ms_get_db_name.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_db_name.setFont(font)
        self.q_ms_get_db_name.setText(_fromUtf8(""))
        self.q_ms_get_db_name.setObjectName(_fromUtf8("q_ms_get_db_name"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.q_ms_dbs_count = QtGui.QLineEdit(self.tab_3)
        self.q_ms_dbs_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_dbs_count.setFont(font)
        self.q_ms_dbs_count.setText(_fromUtf8(""))
        self.q_ms_dbs_count.setObjectName(_fromUtf8("q_ms_dbs_count"))
        self.q_ms_curr_db_name = QtGui.QLineEdit(self.tab_3)
        self.q_ms_curr_db_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_curr_db_name.setFont(font)
        self.q_ms_curr_db_name.setText(_fromUtf8(""))
        self.q_ms_curr_db_name.setObjectName(_fromUtf8("q_ms_curr_db_name"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.q_ms_get_db_name2 = QtGui.QLineEdit(self.tab_3)
        self.q_ms_get_db_name2.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_db_name2.setFont(font)
        self.q_ms_get_db_name2.setText(_fromUtf8(""))
        self.q_ms_get_db_name2.setObjectName(_fromUtf8("q_ms_get_db_name2"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.q_ms_get_tbl_name = QtGui.QLineEdit(self.tab_4)
        self.q_ms_get_tbl_name.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_tbl_name.setFont(font)
        self.q_ms_get_tbl_name.setText(_fromUtf8(""))
        self.q_ms_get_tbl_name.setObjectName(_fromUtf8("q_ms_get_tbl_name"))
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.q_ms_get_tbl_name2 = QtGui.QLineEdit(self.tab_4)
        self.q_ms_get_tbl_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_tbl_name2.setFont(font)
        self.q_ms_get_tbl_name2.setText(_fromUtf8(""))
        self.q_ms_get_tbl_name2.setObjectName(_fromUtf8("q_ms_get_tbl_name2"))
        self.q_ms_tbls_count = QtGui.QLineEdit(self.tab_4)
        self.q_ms_tbls_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_tbls_count.setFont(font)
        self.q_ms_tbls_count.setText(_fromUtf8(""))
        self.q_ms_tbls_count.setObjectName(_fromUtf8("q_ms_tbls_count"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.q_ms_get_column_name = QtGui.QLineEdit(self.tab_5)
        self.q_ms_get_column_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_column_name.setFont(font)
        self.q_ms_get_column_name.setText(_fromUtf8(""))
        self.q_ms_get_column_name.setObjectName(_fromUtf8("q_ms_get_column_name"))
        self.label_15 = QtGui.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(10, 110, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.q_ms_get_column_name3 = QtGui.QLineEdit(self.tab_5)
        self.q_ms_get_column_name3.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_column_name3.setFont(font)
        self.q_ms_get_column_name3.setText(_fromUtf8(""))
        self.q_ms_get_column_name3.setObjectName(_fromUtf8("q_ms_get_column_name3"))
        self.q_ms_columns_count = QtGui.QLineEdit(self.tab_5)
        self.q_ms_columns_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_columns_count.setFont(font)
        self.q_ms_columns_count.setText(_fromUtf8(""))
        self.q_ms_columns_count.setObjectName(_fromUtf8("q_ms_columns_count"))
        self.q_ms_get_column_name2 = QtGui.QLineEdit(self.tab_5)
        self.q_ms_get_column_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_column_name2.setFont(font)
        self.q_ms_get_column_name2.setText(_fromUtf8(""))
        self.q_ms_get_column_name2.setObjectName(_fromUtf8("q_ms_get_column_name2"))
        self.label_14 = QtGui.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(10, 160, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.q_ms_rows_count = QtGui.QLineEdit(self.tab_7)
        self.q_ms_rows_count.setGeometry(QtCore.QRect(10, 30, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_rows_count.setFont(font)
        self.q_ms_rows_count.setText(_fromUtf8(""))
        self.q_ms_rows_count.setObjectName(_fromUtf8("q_ms_rows_count"))
        self.label_25 = QtGui.QLabel(self.tab_7)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.q_ms_query = QtGui.QLineEdit(self.tab_7)
        self.q_ms_query.setGeometry(QtCore.QRect(10, 80, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_query.setFont(font)
        self.q_ms_query.setText(_fromUtf8(""))
        self.q_ms_query.setObjectName(_fromUtf8("q_ms_query"))
        self.label_26 = QtGui.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.q_ms_data_dump = QtGui.QLineEdit(self.tab_7)
        self.q_ms_data_dump.setGeometry(QtCore.QRect(10, 130, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_data_dump.setFont(font)
        self.q_ms_data_dump.setText(_fromUtf8(""))
        self.q_ms_data_dump.setObjectName(_fromUtf8("q_ms_data_dump"))
        self.label_29 = QtGui.QLabel(self.tab_7)
        self.label_29.setGeometry(QtCore.QRect(10, 110, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_24 = QtGui.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(10, 210, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.q_ms_get_row = QtGui.QLineEdit(self.tab_7)
        self.q_ms_get_row.setGeometry(QtCore.QRect(10, 230, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_get_row.setFont(font)
        self.q_ms_get_row.setText(_fromUtf8(""))
        self.q_ms_get_row.setObjectName(_fromUtf8("q_ms_get_row"))
        self.q_ms_exec_cmdshell = QtGui.QLineEdit(self.tab_7)
        self.q_ms_exec_cmdshell.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_ms_exec_cmdshell.setFont(font)
        self.q_ms_exec_cmdshell.setText(_fromUtf8(""))
        self.q_ms_exec_cmdshell.setObjectName(_fromUtf8("q_ms_exec_cmdshell"))
        self.label_22 = QtGui.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.qeTabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_22 = QtGui.QWidget()
        self.tab_22.setObjectName(_fromUtf8("tab_22"))
        self.tabWidget_4 = QtGui.QTabWidget(self.tab_22)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 871, 371))
        self.tabWidget_4.setDocumentMode(True)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.label_3 = QtGui.QLabel(self.tab_9)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.q_union_ms_get_db_name = QtGui.QLineEdit(self.tab_9)
        self.q_union_ms_get_db_name.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_db_name.setFont(font)
        self.q_union_ms_get_db_name.setText(_fromUtf8(""))
        self.q_union_ms_get_db_name.setObjectName(_fromUtf8("q_union_ms_get_db_name"))
        self.label_12 = QtGui.QLabel(self.tab_9)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_17 = QtGui.QLabel(self.tab_9)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.q_union_ms_dbs_count = QtGui.QLineEdit(self.tab_9)
        self.q_union_ms_dbs_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_dbs_count.setFont(font)
        self.q_union_ms_dbs_count.setText(_fromUtf8(""))
        self.q_union_ms_dbs_count.setObjectName(_fromUtf8("q_union_ms_dbs_count"))
        self.q_union_ms_curr_db_name = QtGui.QLineEdit(self.tab_9)
        self.q_union_ms_curr_db_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_curr_db_name.setFont(font)
        self.q_union_ms_curr_db_name.setText(_fromUtf8(""))
        self.q_union_ms_curr_db_name.setObjectName(_fromUtf8("q_union_ms_curr_db_name"))
        self.label_18 = QtGui.QLabel(self.tab_9)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.q_union_ms_get_db_name2 = QtGui.QLineEdit(self.tab_9)
        self.q_union_ms_get_db_name2.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_db_name2.setFont(font)
        self.q_union_ms_get_db_name2.setText(_fromUtf8(""))
        self.q_union_ms_get_db_name2.setObjectName(_fromUtf8("q_union_ms_get_db_name2"))
        self.tabWidget_4.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.label_19 = QtGui.QLabel(self.tab_10)
        self.label_19.setGeometry(QtCore.QRect(10, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.q_union_ms_get_tbl_name = QtGui.QLineEdit(self.tab_10)
        self.q_union_ms_get_tbl_name.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_tbl_name.setFont(font)
        self.q_union_ms_get_tbl_name.setText(_fromUtf8(""))
        self.q_union_ms_get_tbl_name.setObjectName(_fromUtf8("q_union_ms_get_tbl_name"))
        self.label_20 = QtGui.QLabel(self.tab_10)
        self.label_20.setGeometry(QtCore.QRect(10, 110, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.q_union_ms_get_tbl_name2 = QtGui.QLineEdit(self.tab_10)
        self.q_union_ms_get_tbl_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_tbl_name2.setFont(font)
        self.q_union_ms_get_tbl_name2.setText(_fromUtf8(""))
        self.q_union_ms_get_tbl_name2.setObjectName(_fromUtf8("q_union_ms_get_tbl_name2"))
        self.q_union_ms_tbls_count = QtGui.QLineEdit(self.tab_10)
        self.q_union_ms_tbls_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_tbls_count.setFont(font)
        self.q_union_ms_tbls_count.setText(_fromUtf8(""))
        self.q_union_ms_tbls_count.setObjectName(_fromUtf8("q_union_ms_tbls_count"))
        self.label_21 = QtGui.QLabel(self.tab_10)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tabWidget_4.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.q_union_ms_get_column_name = QtGui.QLineEdit(self.tab_11)
        self.q_union_ms_get_column_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_column_name.setFont(font)
        self.q_union_ms_get_column_name.setText(_fromUtf8(""))
        self.q_union_ms_get_column_name.setObjectName(_fromUtf8("q_union_ms_get_column_name"))
        self.label_23 = QtGui.QLabel(self.tab_11)
        self.label_23.setGeometry(QtCore.QRect(10, 110, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.q_union_ms_get_column_name3 = QtGui.QLineEdit(self.tab_11)
        self.q_union_ms_get_column_name3.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_column_name3.setFont(font)
        self.q_union_ms_get_column_name3.setText(_fromUtf8(""))
        self.q_union_ms_get_column_name3.setObjectName(_fromUtf8("q_union_ms_get_column_name3"))
        self.q_union_ms_columns_count = QtGui.QLineEdit(self.tab_11)
        self.q_union_ms_columns_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_columns_count.setFont(font)
        self.q_union_ms_columns_count.setText(_fromUtf8(""))
        self.q_union_ms_columns_count.setObjectName(_fromUtf8("q_union_ms_columns_count"))
        self.q_union_ms_get_column_name2 = QtGui.QLineEdit(self.tab_11)
        self.q_union_ms_get_column_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_column_name2.setFont(font)
        self.q_union_ms_get_column_name2.setText(_fromUtf8(""))
        self.q_union_ms_get_column_name2.setObjectName(_fromUtf8("q_union_ms_get_column_name2"))
        self.label_27 = QtGui.QLabel(self.tab_11)
        self.label_27.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.tab_11)
        self.label_28.setGeometry(QtCore.QRect(10, 160, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_30 = QtGui.QLabel(self.tab_11)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
        self.tab_21 = QtGui.QWidget()
        self.tab_21.setObjectName(_fromUtf8("tab_21"))
        self.q_union_ms_rows_count = QtGui.QLineEdit(self.tab_21)
        self.q_union_ms_rows_count.setGeometry(QtCore.QRect(10, 30, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_rows_count.setFont(font)
        self.q_union_ms_rows_count.setText(_fromUtf8(""))
        self.q_union_ms_rows_count.setObjectName(_fromUtf8("q_union_ms_rows_count"))
        self.label_31 = QtGui.QLabel(self.tab_21)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.q_union_ms_query = QtGui.QLineEdit(self.tab_21)
        self.q_union_ms_query.setGeometry(QtCore.QRect(10, 80, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_query.setFont(font)
        self.q_union_ms_query.setText(_fromUtf8(""))
        self.q_union_ms_query.setObjectName(_fromUtf8("q_union_ms_query"))
        self.label_32 = QtGui.QLabel(self.tab_21)
        self.label_32.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.q_union_ms_data_dump = QtGui.QLineEdit(self.tab_21)
        self.q_union_ms_data_dump.setGeometry(QtCore.QRect(10, 130, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_data_dump.setFont(font)
        self.q_union_ms_data_dump.setText(_fromUtf8(""))
        self.q_union_ms_data_dump.setObjectName(_fromUtf8("q_union_ms_data_dump"))
        self.label_33 = QtGui.QLabel(self.tab_21)
        self.label_33.setGeometry(QtCore.QRect(10, 110, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.tab_21)
        self.label_34.setGeometry(QtCore.QRect(10, 210, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.q_union_ms_get_row = QtGui.QLineEdit(self.tab_21)
        self.q_union_ms_get_row.setGeometry(QtCore.QRect(10, 230, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_get_row.setFont(font)
        self.q_union_ms_get_row.setText(_fromUtf8(""))
        self.q_union_ms_get_row.setObjectName(_fromUtf8("q_union_ms_get_row"))
        self.q_union_ms_exec_cmdshell = QtGui.QLineEdit(self.tab_21)
        self.q_union_ms_exec_cmdshell.setGeometry(QtCore.QRect(10, 180, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_ms_exec_cmdshell.setFont(font)
        self.q_union_ms_exec_cmdshell.setText(_fromUtf8(""))
        self.q_union_ms_exec_cmdshell.setObjectName(_fromUtf8("q_union_ms_exec_cmdshell"))
        self.label_35 = QtGui.QLabel(self.tab_21)
        self.label_35.setGeometry(QtCore.QRect(10, 160, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.tabWidget_4.addTab(self.tab_21, _fromUtf8(""))
        self.qeTabWidget_3.addTab(self.tab_22, _fromUtf8(""))
        self.qeTabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.qeTabWidget_2 = QtGui.QTabWidget(self.tab_2)
        self.qeTabWidget_2.setGeometry(QtCore.QRect(0, 0, 871, 481))
        self.qeTabWidget_2.setDocumentMode(True)
        self.qeTabWidget_2.setObjectName(_fromUtf8("qeTabWidget_2"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.label_4 = QtGui.QLabel(self.tab_13)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_49 = QtGui.QLabel(self.tab_13)
        self.label_49.setGeometry(QtCore.QRect(10, 110, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.q_my_dbs_count = QtGui.QLineEdit(self.tab_13)
        self.q_my_dbs_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_dbs_count.setFont(font)
        self.q_my_dbs_count.setText(_fromUtf8(""))
        self.q_my_dbs_count.setObjectName(_fromUtf8("q_my_dbs_count"))
        self.q_my_curr_db_name = QtGui.QLineEdit(self.tab_13)
        self.q_my_curr_db_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_curr_db_name.setFont(font)
        self.q_my_curr_db_name.setText(_fromUtf8(""))
        self.q_my_curr_db_name.setObjectName(_fromUtf8("q_my_curr_db_name"))
        self.label_51 = QtGui.QLabel(self.tab_13)
        self.label_51.setGeometry(QtCore.QRect(10, 60, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.q_my_get_db_name2 = QtGui.QLineEdit(self.tab_13)
        self.q_my_get_db_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_db_name2.setFont(font)
        self.q_my_get_db_name2.setText(_fromUtf8(""))
        self.q_my_get_db_name2.setObjectName(_fromUtf8("q_my_get_db_name2"))
        self.tabWidget_2.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.label_53 = QtGui.QLabel(self.tab_14)
        self.label_53.setGeometry(QtCore.QRect(10, 60, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.q_my_get_tbl_name2 = QtGui.QLineEdit(self.tab_14)
        self.q_my_get_tbl_name2.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_tbl_name2.setFont(font)
        self.q_my_get_tbl_name2.setText(_fromUtf8(""))
        self.q_my_get_tbl_name2.setObjectName(_fromUtf8("q_my_get_tbl_name2"))
        self.q_my_tbls_count = QtGui.QLineEdit(self.tab_14)
        self.q_my_tbls_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_tbls_count.setFont(font)
        self.q_my_tbls_count.setText(_fromUtf8(""))
        self.q_my_tbls_count.setObjectName(_fromUtf8("q_my_tbls_count"))
        self.label_54 = QtGui.QLabel(self.tab_14)
        self.label_54.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.tabWidget_2.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.label_55 = QtGui.QLabel(self.tab_15)
        self.label_55.setGeometry(QtCore.QRect(10, 60, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.q_my_get_column_name3 = QtGui.QLineEdit(self.tab_15)
        self.q_my_get_column_name3.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_column_name3.setFont(font)
        self.q_my_get_column_name3.setText(_fromUtf8(""))
        self.q_my_get_column_name3.setObjectName(_fromUtf8("q_my_get_column_name3"))
        self.q_my_columns_count = QtGui.QLineEdit(self.tab_15)
        self.q_my_columns_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_columns_count.setFont(font)
        self.q_my_columns_count.setText(_fromUtf8(""))
        self.q_my_columns_count.setObjectName(_fromUtf8("q_my_columns_count"))
        self.q_my_get_column_name2 = QtGui.QLineEdit(self.tab_15)
        self.q_my_get_column_name2.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_get_column_name2.setFont(font)
        self.q_my_get_column_name2.setText(_fromUtf8(""))
        self.q_my_get_column_name2.setObjectName(_fromUtf8("q_my_get_column_name2"))
        self.label_56 = QtGui.QLabel(self.tab_15)
        self.label_56.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.tab_15)
        self.label_57.setGeometry(QtCore.QRect(10, 110, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.tabWidget_2.addTab(self.tab_15, _fromUtf8(""))
        self.tab_17 = QtGui.QWidget()
        self.tab_17.setObjectName(_fromUtf8("tab_17"))
        self.q_my_rows_count = QtGui.QLineEdit(self.tab_17)
        self.q_my_rows_count.setGeometry(QtCore.QRect(10, 30, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_rows_count.setFont(font)
        self.q_my_rows_count.setText(_fromUtf8(""))
        self.q_my_rows_count.setObjectName(_fromUtf8("q_my_rows_count"))
        self.label_66 = QtGui.QLabel(self.tab_17)
        self.label_66.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.q_my_query = QtGui.QLineEdit(self.tab_17)
        self.q_my_query.setGeometry(QtCore.QRect(10, 80, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_my_query.setFont(font)
        self.q_my_query.setText(_fromUtf8(""))
        self.q_my_query.setObjectName(_fromUtf8("q_my_query"))
        self.label_67 = QtGui.QLabel(self.tab_17)
        self.label_67.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.tabWidget_2.addTab(self.tab_17, _fromUtf8(""))
        self.qeTabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_12)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 871, 421))
        self.tabWidget_3.setDocumentMode(True)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.label_8 = QtGui.QLabel(self.tab_16)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_50 = QtGui.QLabel(self.tab_16)
        self.label_50.setGeometry(QtCore.QRect(10, 110, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.q_union_my_dbs_count = QtGui.QLineEdit(self.tab_16)
        self.q_union_my_dbs_count.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_dbs_count.setFont(font)
        self.q_union_my_dbs_count.setText(_fromUtf8(""))
        self.q_union_my_dbs_count.setObjectName(_fromUtf8("q_union_my_dbs_count"))
        self.q_union_my_curr_db_name = QtGui.QLineEdit(self.tab_16)
        self.q_union_my_curr_db_name.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_curr_db_name.setFont(font)
        self.q_union_my_curr_db_name.setText(_fromUtf8(""))
        self.q_union_my_curr_db_name.setObjectName(_fromUtf8("q_union_my_curr_db_name"))
        self.label_52 = QtGui.QLabel(self.tab_16)
        self.label_52.setGeometry(QtCore.QRect(10, 60, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.q_union_my_get_db_name2 = QtGui.QLineEdit(self.tab_16)
        self.q_union_my_get_db_name2.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_get_db_name2.setFont(font)
        self.q_union_my_get_db_name2.setText(_fromUtf8(""))
        self.q_union_my_get_db_name2.setObjectName(_fromUtf8("q_union_my_get_db_name2"))
        self.tabWidget_3.addTab(self.tab_16, _fromUtf8(""))
        self.tab_18 = QtGui.QWidget()
        self.tab_18.setObjectName(_fromUtf8("tab_18"))
        self.label_58 = QtGui.QLabel(self.tab_18)
        self.label_58.setGeometry(QtCore.QRect(10, 60, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.q_union_my_get_tbl_name2 = QtGui.QLineEdit(self.tab_18)
        self.q_union_my_get_tbl_name2.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_get_tbl_name2.setFont(font)
        self.q_union_my_get_tbl_name2.setText(_fromUtf8(""))
        self.q_union_my_get_tbl_name2.setObjectName(_fromUtf8("q_union_my_get_tbl_name2"))
        self.q_union_my_tbls_count = QtGui.QLineEdit(self.tab_18)
        self.q_union_my_tbls_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_tbls_count.setFont(font)
        self.q_union_my_tbls_count.setText(_fromUtf8(""))
        self.q_union_my_tbls_count.setObjectName(_fromUtf8("q_union_my_tbls_count"))
        self.label_59 = QtGui.QLabel(self.tab_18)
        self.label_59.setGeometry(QtCore.QRect(10, 10, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.tabWidget_3.addTab(self.tab_18, _fromUtf8(""))
        self.tab_19 = QtGui.QWidget()
        self.tab_19.setObjectName(_fromUtf8("tab_19"))
        self.label_60 = QtGui.QLabel(self.tab_19)
        self.label_60.setGeometry(QtCore.QRect(10, 60, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.q_union_my_get_column_name3 = QtGui.QLineEdit(self.tab_19)
        self.q_union_my_get_column_name3.setGeometry(QtCore.QRect(10, 130, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_get_column_name3.setFont(font)
        self.q_union_my_get_column_name3.setText(_fromUtf8(""))
        self.q_union_my_get_column_name3.setObjectName(_fromUtf8("q_union_my_get_column_name3"))
        self.q_union_my_columns_count = QtGui.QLineEdit(self.tab_19)
        self.q_union_my_columns_count.setGeometry(QtCore.QRect(10, 30, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_columns_count.setFont(font)
        self.q_union_my_columns_count.setText(_fromUtf8(""))
        self.q_union_my_columns_count.setObjectName(_fromUtf8("q_union_my_columns_count"))
        self.q_union_my_get_column_name2 = QtGui.QLineEdit(self.tab_19)
        self.q_union_my_get_column_name2.setGeometry(QtCore.QRect(10, 80, 841, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_get_column_name2.setFont(font)
        self.q_union_my_get_column_name2.setText(_fromUtf8(""))
        self.q_union_my_get_column_name2.setObjectName(_fromUtf8("q_union_my_get_column_name2"))
        self.label_61 = QtGui.QLabel(self.tab_19)
        self.label_61.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.tab_19)
        self.label_62.setGeometry(QtCore.QRect(10, 110, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.tabWidget_3.addTab(self.tab_19, _fromUtf8(""))
        self.tab_20 = QtGui.QWidget()
        self.tab_20.setObjectName(_fromUtf8("tab_20"))
        self.q_union_my_rows_count = QtGui.QLineEdit(self.tab_20)
        self.q_union_my_rows_count.setGeometry(QtCore.QRect(10, 30, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_rows_count.setFont(font)
        self.q_union_my_rows_count.setText(_fromUtf8(""))
        self.q_union_my_rows_count.setObjectName(_fromUtf8("q_union_my_rows_count"))
        self.label_68 = QtGui.QLabel(self.tab_20)
        self.label_68.setGeometry(QtCore.QRect(10, 10, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.q_union_my_query = QtGui.QLineEdit(self.tab_20)
        self.q_union_my_query.setGeometry(QtCore.QRect(10, 80, 841, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.q_union_my_query.setFont(font)
        self.q_union_my_query.setText(_fromUtf8(""))
        self.q_union_my_query.setObjectName(_fromUtf8("q_union_my_query"))
        self.label_69 = QtGui.QLabel(self.tab_20)
        self.label_69.setGeometry(QtCore.QRect(10, 60, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.tabWidget_3.addTab(self.tab_20, _fromUtf8(""))
        self.qeTabWidget_2.addTab(self.tab_12, _fromUtf8(""))
        self.qeTabWidget.addTab(self.tab_2, _fromUtf8(""))
        QueryEditorForm.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(QueryEditorForm)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 861, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMenu = QtGui.QMenu(self.menuBar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        QueryEditorForm.setMenuBar(self.menuBar)
        self.qsSave = QtGui.QAction(QueryEditorForm)
        self.qsSave.setObjectName(_fromUtf8("qsSave"))
        self.qsRestore = QtGui.QAction(QueryEditorForm)
        self.qsRestore.setObjectName(_fromUtf8("qsRestore"))
        self.menuMenu.addAction(self.qsSave)
        self.menuMenu.addAction(self.qsRestore)
        self.menuBar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(QueryEditorForm)
        self.qeTabWidget.setCurrentIndex(0)
        self.qeTabWidget_3.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.qeTabWidget_2.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QueryEditorForm)

    def retranslateUi(self, QueryEditorForm):
        QueryEditorForm.setWindowTitle(QtGui.QApplication.translate("QueryEditorForm", "Enema - Query Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QueryEditorForm", "------current db name------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (not in substring method, multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of databases------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("QueryEditorForm", "bases", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (not in substring method,multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of tables------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("QueryEditorForm", "tables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (not in substring method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("QueryEditorForm", "------columns count------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (ordinal_postition method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("QueryEditorForm", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("QueryEditorForm", "------rows count in selected table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("QueryEditorForm", "------run query------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("QueryEditorForm", "------data dump------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("QueryEditorForm", "------get row from temp table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("QueryEditorForm", "------exec xp_cmdshell------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("QueryEditorForm", "etc", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget_3.setTabText(self.qeTabWidget_3.indexOf(self.tab_8), QtGui.QApplication.translate("QueryEditorForm", "Error-based", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("QueryEditorForm", "------current db name------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (not in substring method, multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of databases------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), QtGui.QApplication.translate("QueryEditorForm", "bases", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (not in substring method,multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of tables------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), QtGui.QApplication.translate("QueryEditorForm", "tables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (not in substring method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("QueryEditorForm", "------columns count------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (ordinal_postition method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (not in array method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), QtGui.QApplication.translate("QueryEditorForm", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("QueryEditorForm", "------rows count in selected table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("QueryEditorForm", "------run query------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("QueryEditorForm", "------data dump------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("QueryEditorForm", "------get row from temp table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("QueryEditorForm", "------exec xp_cmdshell------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_21), QtGui.QApplication.translate("QueryEditorForm", "etc", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget_3.setTabText(self.qeTabWidget_3.indexOf(self.tab_22), QtGui.QApplication.translate("QueryEditorForm", "Union-Based", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget.setTabText(self.qeTabWidget.indexOf(self.tab), QtGui.QApplication.translate("QueryEditorForm", "mssql", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("QueryEditorForm", "------current db name------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (limit method, multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of databases------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_13), QtGui.QApplication.translate("QueryEditorForm", "bases", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (limit method,multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of tables------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_14), QtGui.QApplication.translate("QueryEditorForm", "tables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (limit method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("QueryEditorForm", "------columns count------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (ordinal_postition method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_15), QtGui.QApplication.translate("QueryEditorForm", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("QueryEditorForm", "------rows count in selected table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("QueryEditorForm", "------run query------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_17), QtGui.QApplication.translate("QueryEditorForm", "etc", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget_2.setTabText(self.qeTabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("QueryEditorForm", "Error-based", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("QueryEditorForm", "------current db name------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("QueryEditorForm", "------get db name (limit method, multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of databases------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_16), QtGui.QApplication.translate("QueryEditorForm", "bases", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("QueryEditorForm", "------get table name (limit method,multithreaded)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("QueryEditorForm", "------count of tables------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_18), QtGui.QApplication.translate("QueryEditorForm", "tables", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (limit method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("QueryEditorForm", "------columns count------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("QueryEditorForm", "------get column name (ordinal_postition method)------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_19), QtGui.QApplication.translate("QueryEditorForm", "columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("QueryEditorForm", "------rows count in selected table------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("QueryEditorForm", "------run query------", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_20), QtGui.QApplication.translate("QueryEditorForm", "etc", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget_2.setTabText(self.qeTabWidget_2.indexOf(self.tab_12), QtGui.QApplication.translate("QueryEditorForm", "Union-based", None, QtGui.QApplication.UnicodeUTF8))
        self.qeTabWidget.setTabText(self.qeTabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("QueryEditorForm", "mysql", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("QueryEditorForm", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.qsSave.setText(QtGui.QApplication.translate("QueryEditorForm", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.qsRestore.setText(QtGui.QApplication.translate("QueryEditorForm", "Restore defaults", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    QueryEditorForm = QtGui.QMainWindow()
    ui = Ui_QueryEditorForm()
    ui.setupUi(QueryEditorForm)
    QueryEditorForm.show()
    sys.exit(app.exec_())

